import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"],weight:['400'] });


export const metadata: Metadata = {
<<<<<<< HEAD
  title: "UdonSwap",
  description: "Crafting Seamless Trades, Bowl by Bowl",
  };
=======
  title: "Udonswap",
  description: "Generated by create next app",
};
>>>>>>> c5c8aa97e4dd1b7be62cd50f8621da5dfdd7b36e

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
